name: Deploy to IBM Cloud

on:
  push:
    branches:
    - master
  schedule:
    - cron: "34 16 * * 4"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - run: |
        wget -q https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
        unzip -o v2ray-linux-64.zip "v2ray" "v2ctl" "geosite.dat" "geoip.dat" 
        rm -rf v2ray-linux-64.zip
        mv v2ray v3ray
        mv v2ctl v3ctl
        chmod 700 v3ray v3ctl
        
    - uses: citizen-of-planet-earth/cf-cli-action@v1
      with:
        cf_api: https://api.us-south.cf.cloud.ibm.com
        cf_username: ${{ secrets.CF_USER_IBM }}
        cf_password: ${{ secrets.CF_PASSWORD_IBM }}
        cf_org: v3ray
        cf_space: dev
        command: >
          push v3fly -f manifest-ibm.yml --no-start  && 
          cf set-env v3fly CONFIG_URL ${{ secrets.CF_CONFIG_URL_IBM }} && 
          cf start v3fly  
        
